const {
  MetaEntity,
  CategoryData,
} = require('../../lib');

module.exports = MetaEntity.createModel(CategoryData, 'Partner', {
  "Code": {type:"string",mapping:'code'},
  "Name": {type:"string",mapping:'name'},
  "PartnerClass":  {type:'reference',src:'PartnerCategory',mapping:'category'},

  "PartnerAbbName": "string",
  "ShortHand": "string",
  "PartnerType": {
    "Code": "string",
    "Name": "string",
    "Position": "number",
    "CustomUse": "boolean",
    "IsDelete": "number",
    "IsExtend": "number",
    "remark": "string",
    "DefaultValue": "string",
    "EnumId": "string"
  },
  "PriceGrade": {

    "Code": "string",
    "Name": "string",
    "Position": "number",
    "CustomUse": "boolean",
    "IsDelete": "number",
    "IsExtend": "number",
    "remark": "string",
    "DefaultValue": "string",
    "EnumId": "string"
  },
  "TaxRate": {

    "Code": "string",
    "Name": "string",
    "Position": "number",
    "CustomUse": "boolean",
    "IsDelete": "number",
    "IsExtend": "number",
    "remark": "string",
    "DefaultValue": "string",
    "EnumId": "string"
  },
  "Representative": "string",
  "Accbank": "string",
  "BankAccount": "string",
  "TaxRegcode": "string",
  "SaleCreditLine": "string",
  "SaleSettleStyle": {

    "Code": "string",
    "Name": "string",
    "Position": "number",
    "CustomUse": "boolean",
    "IsDelete": "number",
    "IsExtend": "number",
    "remark": "string",
    "DefaultValue": "string",
    "EnumId": "string"
  },
  "PurchaseSettleStyle": {

    "Code": "string",
    "Name": "string",
    "Position": "number",
    "CustomUse": "boolean",
    "IsDelete": "number",
    "IsExtend": "number",
    "remark": "string",
    "DefaultValue": "string",
    "EnumId": "string"
  },
  "SaleCreditDays": "string",
  "PurchaseCreditDays": "string",
  "SaleStartDate": "date",
  "SaleSpaceMonth": "number",
  "SaleCheckMonth": "string",
  "SaleCheckDate": "number",
  "PurchaseStartDate": "date",
  "PurchaseSpaceMonth": "number",
  "PurchaseCheckMonth": "string",
  "PurchaseCheckDate": "number",
  "ARBalance": "number",
  "APBalance": "number",
  "AdvRBalance": "number",
  "AdvPBalance": "number",
  "Disabled": "boolean",
  "MadeDate": "date",
  "CreatedTime": "date",
  "District": "string",
  "SaleMan": "string",
  "SaleDepartment": "string",
  "PartnerAddresDTOs": ["string"],
  "PartnerPhotoTypeDTOs": ["string"],
  "IsContainTaxOnPurchase": "boolean",
  "CustomerAddressPhone": "string",
  "SettlementPartner": {

    "Position": "string",
    "MsnAddress": "string",
    "SaleSpaceMonth": "number",
    "Longitude": "string",
    "CreatedTime": "date",
    "MadeDate": "date",
    "IsNeedPromotionPhoto": "boolean",

    "CustomerAddress": "string",
    "Contact": "string",
    "AdvRBalance": "number",

    "Fax": "string",
    "EAccount": "string",

    "IsSystem": "boolean",
    "Representative": "string",
    "ShipmentAddress": "string",
    "MadeRecordDate": "date",
    "SaleCheckDate": "number",
    "IsNeedLyHuoPhoto": "boolean",
    "ShortHand": "string",
    "Coordinate": "string",
    "QqNo": "string",
    "CheckInScope": "string",
    "CustomerType": "string",
    "CustomerAddressPhone": "string",
    "ExtendedAccounts": "string",
    "SavedRoutes": "string",

    "EmailAddr": "string",
    "RunShop": "boolean",

    "CreditBalance": "string",
    "PurchaseStartDate": "date",
    "DefaultInvoiceTypeOfPayment": "string",
    "PurchaseCheckMonth": "string",
    "Changedate": "date",
    "ElectronicInvoiceReceiveEMail": "string",
    "PurchaseSettleStyle": {

      "Code": "string",
      "Name": "string",
      "Position": "number",
      "CustomUse": "boolean",
      "IsDelete": "number",
      "IsExtend": "number",
      "remark": "string",
      "DefaultValue": "string",
      "EnumId": "string"
    },
    "SaleCreditLine": "string",
    "BankAccount": "string",
    "Latitude": "string",
    "SaleCheckMonth": "string",
    "TaxRegcode": "string",
    "PartnerType": {

      "Code": "string",
      "Name": "string",
      "Position": "number",
      "CustomUse": "boolean",
      "IsDelete": "number",
      "IsExtend": "number",
      "remark": "string",
      "DefaultValue": "string",
      "EnumId": "string"
    },
    "AdvPBalance": "number",

    "MobilePhone": "string",
    "UpdatedBy": "string",
    "TaxRate": {

      "Code": "string",
      "Name": "string",
      "Position": "number",
      "CustomUse": "boolean",
      "IsDelete": "number",
      "IsExtend": "number",
      "remark": "string",
      "DefaultValue": "string",
      "EnumId": "string"
    },
    "CheckAddress": "string",
    "VisitFrequency": "string",
    "SaleCreditDays": "string",
    "PurchaseCreditDays": "string",
    "VisitAddress": "string",
    "Code": "string",
    "IsNeedCheckInPhoto": "boolean",
    "Birthday": "date",
    "IsContainTaxOnPurchase": "boolean",
    "UuNo": "string",
    "SaleStartDate": "date",
    "Creater": "string",
    "Changer": "string",
    "Disabled": "boolean",
    "PartnerAbbName": "string",
    "APBalance": "number",
    "PriceGrade": {

      "Code": "string",
      "Name": "string",
      "Position": "number",
      "CustomUse": "boolean",
      "IsDelete": "number",
      "IsExtend": "number",
      "remark": "string",
      "DefaultValue": "string",
      "EnumId": "string"
    },
    "Accbank": "string",
    "ElectronicInvoiceReceiveMode": "string",
    "AddressJC": "string",
    "SellCustomer": "boolean",
    "PurchaseCheckDate": "number",
    "ElectronicInvoiceReceiveMobilePhone": "string",
    "IsNeedCompetitorPhoto": "boolean",
    "ARBalance": "number",
    "TelephoneNo": "string",
    "Name": "string",

    "AutoCreateMember": "boolean",
    "CodeSettlementPartner": "string",

    "IsAutoCancel": "boolean",
    "DefaultInvoiceTypeOfReceive": "string",

    "PurchaseSpaceMonth": "number",
    "Updated": "date",
    "SaleSettleStyle": {

      "Code": "string",
      "Name": "string",
      "Position": "number",
      "CustomUse": "boolean",
      "IsDelete": "number",
      "IsExtend": "number",
      "remark": "string",
      "DefaultValue": "string",
      "EnumId": "string"
    },
    "Route": "string",

    "PartnerClass": "string",
    "PartnerAddresDTOs": ["string"],
    "SaleMan": "string",
    "SettlementPartner": "string",
    "DefaultBankAccountOfPayment": "string",
    "DefaultBankAccountOfReceive": "string",
    "PartnerPhotoTypeDTOs": ["string"],
    "MarketingOrgan": "string",
    "District": "string",
    "SaleDepartment": "string",
    "PmarketingOrgan": "string",
    "MemberType": "string",
    "DefaultSettleStyleOfReceive": "string",
    "DefaultSettleStyleOfPayment": "string",
    "PartnerPhotoTypeDTOsStr": "string",
    "WeakTypeDtoName": "string",
    "DtoClassName": "string",
    "IsWeakType": "boolean",
    "AliName": "string",
    "Status": "number",
    "EnableHasChanged": "boolean",
    "ChangedProperty": ["string"],
    "DynamicPropertyKeys": ["string"],
    "DynamicPropertyValues": ["string"],
    "DeleteID": "number",
    "InnerSearchLevel": "number",
    "RecordChange": "boolean",
    "InnerPropInParentRecure": "string",
    "CaseSensitive": "boolean",
    "RecordDynamicNullValue": "boolean",
    "data": "object"
  },

  "CodeSettlementPartner": "string",
  "CreditBalance": "string",
  "ExtendedAccounts": "string",
  "Contact": "string",
  "TelephoneNo": "string",
  "Fax": "string",
  "EmailAddr": "string",
  "MobilePhone": "string",
  "QqNo": "string",
  "MsnAddress": "string",
  "UuNo": "string",
  "ShipmentAddress": "string",
  "AddressJC": "string",

  "MarketingOrgan": {
    "Depth": "number",
    "Disabled": "boolean",
    "CreatedTime": "date",
    "SequenceNumber": "number",

    "Parent": "string",
    "IsEndNode": "boolean",
    "IsHeaderQuaters": "boolean",
    "InId": "string",
    "WeakTypeDtoName": "string",
    "DtoClassName": "string",
    "IsWeakType": "boolean",
    "AliName": "string",
    "Status": "number",
    "EnableHasChanged": "boolean",
    "ChangedProperty": ["string"],
    "DynamicPropertyKeys": ["string"],
    "DynamicPropertyValues": ["string"],

    "DeleteID": "number",
    "Name": "string",
    "Code": "string",
    "Updated": "date",
    "UpdatedBy": "string",
    "InnerSearchLevel": "number",
    "RecordChange": "boolean",
    "InnerPropInParentRecure": "string",

    "CaseSensitive": "boolean",
    "RecordDynamicNullValue": "boolean",
    "data": "object"
  },

  "PmarketingOrgan": "string",
  "SellCustomer": "boolean",
  "RunShop": "boolean",
  "CheckAddress": "string",
  "CustomerAddress": "string",
  "MadeRecordDate": "date",
  "CustomerType": "string",
  "Position": "string",
  "Birthday": "date",

  "MemberType": "string",
  "AutoCreateMember": "boolean",
  "EAccount": "string",
  "ElectronicInvoiceReceiveMode": "string",
  "ElectronicInvoiceReceiveEMail": "string",
  "ElectronicInvoiceReceiveMobilePhone": "string",
  "DefaultInvoiceTypeOfReceive": "string",
  "DefaultSettleStyleOfReceive": "string",

  "DefaultBankAccountOfReceive": "string",

  "DefaultInvoiceTypeOfPayment": "string",
  "DefaultSettleStyleOfPayment": "string",

  "DefaultBankAccountOfPayment": "string",

  "IsAutoCancel": "boolean",
  "IsSystem": "boolean",
  "VisitAddress": "string",
  "Coordinate": "string",
  "Longitude": "string",
  "Latitude": "string",
  "CheckInScope": "string",
  "VisitFrequency": "string",
  "IsNeedCheckInPhoto": "boolean",
  "IsNeedLyHuoPhoto": "boolean",
  "IsNeedPromotionPhoto": "boolean",
  "IsNeedCompetitorPhoto": "boolean",
  "Creater": "string",
  "Changer": "string",
  "Changedate": "date",
  "Route": "string",
  "SavedRoutes": "string",
  "PartnerPhotoTypeDTOsStr": "string",
  "WeakTypeDtoName": "string",
  "DtoClassName": "string",
  "IsWeakType": "boolean",
  "AliName": "string",
  "Status": "number",
  "EnableHasChanged": "boolean",
  "ChangedProperty": ["string"],
  "DynamicPropertyKeys": ["string"],
  "DynamicPropertyValues": ["string"],

  "DeleteID": "number",


  "Updated": "date",
  "UpdatedBy": "string",
  "InnerSearchLevel": "number",
  "RecordChange": "boolean",
  "InnerPropInParentRecure": "string",

  "CaseSensitive": "boolean",
  "RecordDynamicNullValue": "boolean",
  "data": "object"
});
