const {
  MetaEntity,
  CompositeData,
} = require('../../lib');

module.exports = MetaEntity.create(CompositeData, 'ReceivePayment', {
  "Code": {type:"string",mapping:'code'},
  "Name": {type:"string",mapping:'name'},
  "VoucherDate": "date",
  "Partner": "Partner",
  "BusiType": "BusinessType",
  "PartnerAccBank": "string",
  "PartnerBankAccount": "string",
  "Department": "Department",
  "Person": "Person",
  "Currency": "Currency",
  "ExchangeRate": "number",
  "OrigPaymentAmount": "number",
  "OrigAllowances": "number",
  "PaymentAmount": "number",
  "Allowances": "number",
  "Error": "number",
  "VoucherType": "VoucherType",
  "SourceVoucherCode": "string",
  "ExternalCode": "string",
  "Project": "Project",
  "PayReqVoucherCode": "string",
  "PurchaseOrderCode": "string",
  "CancelOrigAmount": "number",
  "CancelAmount": "number",
  "pubuserdefdecm": "number",
  "CancelState": {
    "Code": "string",
    "Name": "string",
  },
  "PayReqVoucherID": "string",
  "PurchaseOrderID": "string",
  "OrigOverPayment": "number",
  "IsModifiedCode": "bool",
  "IsAuto": "bool",
  "IsReceiveFlag": "bool",
  "DocId": "string",
  "OverPayment": "number",
  "pubuserdefdecm": "number",
  "Memo": "string",
  "Maker": "string",
  "Reviser": "string",
  "Auditor": "string",
  "AuditedDate": "date",
  "VoucherState": "VoucherState",
  "MarketingOrgan": "MarketingOrgan",
  "PrintCount": "number",
  "ArapMultiSettleDetails": [{
    "SettleStyle": "SettleStyle",
    "BankAccount": "BankAccount",
    "OrigAmount": "number",
    "Amount": "number",
    "DocumentCode": "string",
    "Status": "string",
    "Code": "string",
  }],
  "Details": [{
    "PayReqVoucherID": "string",
    "PayReqVoucherDetailID": "string",
    "PayReqVoucherCode": "string",
    "VoucherType": "VoucherType",
    "BusiType": "BusinessType",
    "SourceVoucherMemo": "string",
    "SaleOrderCode": "string",
    "SaleOrderID": "string",
    "VoucherDate": "date",
    "VoucherCode": "string",
    "SourceOrderCode": "string",
    "PurchaseOrderCode": "string",
    "PurchaseOrderID": "string",
    "Project": "Project",
    "DetailName": "string",
    "DetailProject": "Project",
    "Department": "Department",
    "Person": "Person",
    "DetailCode": "string",
    "Currency": "Currency",
    "ExchangeRate": "number",
    "OrigAmount": "number",
    "Amount": "number",
    "OrigNoSettleAmount": "number",
    "OrigCurrentAmount": "number",
    "CurrentAmount": "number",
    "VoucherTimeStamp": "string",
    "OrigAllowancesAmount": "number",
    "AllowancesAmount": "number",
    "VoucherID": "string",
    "VoucherDetailID": "string",
    "DetailID": "string",

    "ArrivalDate": "date",
    "Status": "string",
    "Code": "string",
  }]
});
