
{
  "VoucherDate": "date",
  "Partner": "Partner",
  "BusiType": "BusinessType",
  "PartnerAccBank": "string",
  "PartnerBankAccount": "string",
  "Department": "Department",
  "Person": "Person",
  "Currency": "Currency",
  "ExchangeRate": "number",
  "OrigPaymentAmount": "number",
  "OrigAllowances": "number",
  "PaymentAmount": "number",
  "Allowances": "number",
  "Error": "number",
  "VoucherType": null,
  "SourceVoucherCode": "",
  "ExternalCode": "",
  "Project": "Project",
  "PayReqVoucherCode": "",
  "PurchaseOrderCode": "",
  "CancelOrigAmount": "number",
  "CancelAmount": "number",
  "pubuserdefdecm" : "number",
  "CancelState": {
    "Code": "NoCancel",
    "Name": "未核销"
  },
  "PayReqVoucherID": null,
  "PurchaseOrderID": null,
  "OrigOverPayment": "number",
  "IsModifiedCode": false,
  "IsAuto": false,
  "IsReceiveFlag": false,
  "DocId": "",
  "OverPayment": "number",
  "pubuserdefdecm" : "number",
  "Memo": "",
  "Maker": "tplusdemo129",
  "Reviser": "",
  "Auditor": "tplusdemo129",
  "AuditedDate": "date",
  "VoucherState": "VoucherState",
  "MarketingOrgan": "MarketingOrgan",
  "PrintCount": "number",
  "ArapMultiSettleDetails": [{
    "SettleStyle",
    "BankAccount",
    "OrigAmount",
    "Amount",
    "DocumentCode",
    "Status",
    "Code"
  }],
  "Details": [{
    "PayReqVoucherID",
    "PayReqVoucherDetailID",
    "PayReqVoucherCode",
    "VoucherType",
    "BusiType",
    "SourceVoucherMemo",
    "SaleOrderCode",
    "SaleOrderID",
    "VoucherDate",
    "VoucherCode",
    "SourceOrderCode",
    "PurchaseOrderCode",
    "PurchaseOrderID",
    "Project",
    "DetailName",
    "DetailProject",
    "Department",
    "Person",
    "DetailCode",
    "Currency",
    "ExchangeRate",
    "OrigAmount",
    "Amount",
    "OrigNoSettleAmount",
    "OrigCurrentAmount",
    "CurrentAmount",
    "VoucherTimeStamp",
    "OrigAllowancesAmount",
    "AllowancesAmount",
    "VoucherID",
    "VoucherDetailID",
    "DetailID",
    "idcurrency",
    "idperson",
    "IdMember",
    "iddepartment",
    "ArrivalDate",
    "Status",
    "Code"
  }],
}
