const {
  MetaEntity,
  BaseData,
} = require('../../lib');

module.exports = MetaEntity.create(BaseData, 'Unit',{
  "RateDescription": "string",
  "IsGroup": "bool",
  "IsMainUnit": "bool",
  "ChangeType": "string",
  "ChangeType1": "string",
  "ChangeRate": "number",
  "IsSingleUnit": "bool",
  "Disabled": "bool",
  "MadeDate": "date",
  "CreatedTime": "date",
  "IdunitGroup": "string",
  "UnitGroup": "string",
  "WeakTypeDtoName": "string",
  "DtoClassName": "string",
  "IsWeakType": "bool",
  "AliName": "string",
  "Status": "number",
  "EnableHasChanged": "bool",
  "ChangedProperty": ["string"],
  "DynamicPropertyKeys": ["string"],
  "DynamicPropertyValues": ["string"],
  "DeleteID": "number",
  "Code": {type:"string",mapping:'code'},
  "Name": {type:"string",mapping:'name'},
  "Updated": "date",
  "UpdatedBy": "string",
  "InnerSearchLevel": "number",
  "RecordChange": "bool",
  "InnerPropInParentRecure": "string",

  "CaseSensitive": "bool",
  "RecordDynamicNullValue": "bool",
  "data": "object"
})
