module.exports = {
  "DeliveryDate": new Date(Date.UTC(1,0,1,0,0,0)),
  "DiscountRate": 1,
  "ExchangeRate": 1,
  "Address": "123",
  "LinkMan": "123",
  "ReciveType": {},
  "CustomerPhone": "123",
  "AuditedDate": new Date(Date.UTC(1,0,1,0,0,0)),
  "Clerk": "[object Object]",
  "Currency": {},
  "Department": {},
  "BusinessType": {},
  "SettleCustomer": {},
  "Warehouse": {},
  "DataSource": {},
  "Customer": {},
  "ChangeDate": new Date(Date.UTC(1,0,1,0,0,0)),
  "VoucherState": {},
  "VoucherDate": new Date(Date.UTC(2019,7,5,0,0,0)),
  "Maker": "tplusdemo101",
  "MakerId": 810,
  "DirectCallSource": {},
  "Code": "SO-2019-08-0000000001-0054",
  "data": {},
  "Subscriptions": [
    {
      "SettleStyle": {},
      "BankAccount": {},
      "OrigAmount": 5000,
      "Amount": 5000,
      "Status": "0"
    }
  ],
  "SaleOrderDetails": [
    {
      "DeliveryDate": new Date(Date.UTC(1970,0,1,0,0,0)),
      "PurchaseQuantity": "-276.8",
      "LastModifiedField": "false",
      "IsNoModify": "7470",
      "IsPresent": true,
      "DataSource": {},
      "PriceStrategyTypeName": "0",
      "Closer":  new Date(Date.UTC(1,0,1,0,0,0)),
      //"IsPresent": false,
      "OrigPrice": "0",
      "OrigDiscountAmount": 5,
      "OrigDiscount": "0.03",
      "LatestCost": "-276.8",
      "LatestSaleOrigTaxPrice": "1000",
      "LowestSalePrice": "0",
      "SingleInvGrossProfit": "[object Object]",
      "OutFields": {},
      "Unit": {},
      "Unit2": "0.008333",
      "Quantity": 1,
      "Quantity2": "120",
      "AvailableQuantity": "0",
      "ExistingQuantity": "0",
      "AvailableCompositionQuantity": "0",
      "ExistingCompositionQuantity": "0",
      "Project": {},
      "data": {}
    }
  ],
  "status": "invalid",
  "createBy": "user001"
}
