module.exports = {
  "Mobilephone": null,
  "DeliveryDate": new Date("1900-12-31T16:00:00.000Z"),
  "DiscountRate": 1,
  "ExchangeRate": 1,
  "DeliveryMode": null,
  "Address": "123",
  "LinkMan": "123",
  "ReciveType": {
    "Code": "05",
    "Name": "其它",
    "status": "invalid",
    "createBy": null,
    "createAt": new Date("2019-08-29T09:00:54.021Z"),
    "updateBy": null,
    "updateAt": new Date("2019-08-29T09:00:54.021Z"),
    "ts": "1567069254021",
    "id": "RQHH8mpxwT"
  },
  "ContractCode": null,
  "OrigEarnestMoney": 0,
  "Memo": "",
  "ContactPhone": "",
  "CustomerPhone": "123",
  "IsAutoGenerateSaleOrderBOM": false,
  "IsAutoGenerateRouting": false,
  "SourceVoucherId": null,
  "SourceVoucherCode": null,
  "Auditor": null,
  "Reviser": null,
  "AuditedDate": new Date("1900-12-31T16:00:00.000Z"),
  "IsModifiedCode": false,
  "ExternalVoucherCode": null,
  "Project": null,
  "Clerk": "[object Object]",
  "Currency": {
    "CalDirection": null,
    "AccountDate": null,
    "AccountYear": null,
    "ExChangeRateType": null,
    "Code": "RMB",
    "Name": "人民币",
    "status": "invalid",
    "createBy": null,
    "createAt": new Date("2019-08-29T09:00:54.022Z"),
    "updateBy": null,
    "updateAt": new Date("2019-08-29T09:00:54.022Z"),
    "ts": "1567069254022",
    "id": "hBa_fslCyx"
  },
  "Department": "[object Object]",
  "BusinessType": {
    "Code": "15",
    "Name": "普通销售",
    "RdStyleOut": null,
    "status": "invalid",
    "createBy": null,
    "createAt": new Date("2019-08-29T09:00:54.025Z"),
    "updateBy": null,
    "updateAt": new Date("2019-08-29T09:00:54.025Z"),
    "ts": "1567069254025",
    "id": "3RSNDrh0XC"
  },
  "SourceVoucherType": null,
  "SettleCustomer": {
    "Code": "00000001",
    "Name": "广东JH",
    "PartnerAbbName": "广东JH",
    "PartnerType": null,
    "PriceGrade": null,
    "TaxRate": null,
    "Representative": "",
    "SaleSettleStyle": null,
    "PurchaseSettleStyle": null,
    "SaleCreditDays": null,
    "District": null,
    "SettlementPartner": {
      "PurchaseSettleStyle": null,
      "PartnerType": null,
      "TaxRate": null,
      "PriceGrade": null,
      "SaleSettleStyle": null
    },
    "UuNo": null,
    "MarketingOrgan": null,
    "status": "invalid",
    "createBy": null,
    "createAt": new Date("2019-08-29T09:00:54.000Z"),
    "updateBy": null,
    "updateAt": new Date("2019-08-29T09:00:54.000Z"),
    "ts": "1567069253999",
    "id": "GQz7noxlW"
  },
  "Warehouse": "[object Object]",
  "IsNoModify": null,
  "PrintCount": 0,
  "IsSeparateByWareHouse": false,
  "Closer": null,
  "CloseDate": null,
  "DataSource": {},
  "Customer": {
    "Code": "00000001",
    "Name": "广东JH",
    "PartnerAbbName": "广东JH",
    "PartnerType": null,
    "PriceGrade": null,
    "TaxRate": null,
    "Representative": "",
    "SaleSettleStyle": null,
    "PurchaseSettleStyle": null,
    "SaleCreditDays": null,
    "District": null,
    "SettlementPartner": {
      "PurchaseSettleStyle": null,
      "PartnerType": null,
      "TaxRate": null,
      "PriceGrade": null,
      "SaleSettleStyle": null
    },
    "UuNo": null,
    "MarketingOrgan": null,
    "status": "invalid",
    "createBy": null,
    "createAt": new Date("2019-08-29T09:00:54.000Z"),
    "updateBy": null,
    "updateAt": new Date("2019-08-29T09:00:54.000Z"),
    "ts": "1567069253999",
    "id": "GQz7noxlW"
  },
  "Changer": null,
  "ChangeDate": new Date("1900-12-31T16:00:00.000Z"),
  "Member": null,
  "VoucherState": {
    "Code": "00",
    "Name": "未审",
    "status": "invalid",
    "createBy": null,
    "createAt": new Date("2019-08-29T09:00:54.024Z"),
    "updateBy": null,
    "updateAt": new Date("2019-08-29T09:00:54.024Z"),
    "ts": "1567069254024",
    "id": "xZNtoOPZmR"
  },
  "VoucherDate": new Date("2019-08-04T16:00:00.000Z"),
  "Maker": "tplusdemo101",
  "MakerId": 810,
  "DirectCallSource": {},
  "Status": 0,
  "Code": "SO-2019-08-0000000001-0054",
  "Subscriptions": [
    {
      "SettleStyle": {
        "id": "15",
        "Code": "997",
        "Name": "转账"
      },
      "BankAccount": {
        "id": 1,
        "Code": "现金",
        "Name": "现金",
        "NewBalance": 5188.2
      },
      "OrigProjectAmount": 0,
      "OrigAmount": 5000,
      "Amount": 5000,
      "Status": 0,
      "id": 1390
    }
  ],
  "SaleOrderDetails": [
    {
      "Project": {
        "id": "3643",
        "Code": "...1",
        "Name": "1-1-101",
        "DynamicPropertyKeys": [
          "priuserdefnvc4",
          "priuserdefnvc5",
          "priuserdefnvc2",
          "priuserdefnvc3",
          "priuserdefnvc1",
          "withoutbargain",
          "haseverchanged",
          "ismodifiedcode",
          "isbatch_dy",
          "isqualityperiod_dy",
          "issingleunit_dy",
          "islaborcost_dy",
          "notcheckcolbyinvprop",
          "issingle_dy",
          "isfix_dy",
          "idunit_dy",
          "rateofunitgroup_dy",
          "allrateofunitgroup_dy",
          "islocation_dy"
        ],
        "DynamicPropertyValues": [
          "",
          "",
          "",
          "",
          "",
          0,
          "1",
          1,
          false,
          false,
          false,
          false,
          "Batch",
          true,
          false,
          "434",
          [
            {
              "Name": "套",
              "RateOfExchange": 120
            },
            {
              "Name": "平米",
              "RateOfExchange": 1
            }
          ],
          [
            {
              "Name": "套",
              "RateOfExchange": 120
            },
            {
              "Name": "平米",
              "RateOfExchange": 1
            }
          ],
          false
        ],
        "Specification": "A",
        "ImageFile": "ca5355e4-f9c4-43d5-9c3e-343e86d3af44.jpg",
        "priuserdefdecm2": null,
        "priuserdefdecm1": null,
        "priuserdefnvc1": "",
        "priuserdefdecm3": null,
        "priuserdefdecm4": null,
        "priuserdefdecm5": null,
        "priuserdefnvc2": "",
        "priuserdefnvc3": "",
        "priuserdefnvc4": "",
        "priuserdefnvc5": "",
        "ProductInfo": null
      },
      "Inventory": {
        "id": "434",
        "Code": "2",
        "Name": "平米"
      },
      "freeitem3": 1,
      "InventoryBarCode": "",
      "DataSource": {
        "id": "2498",
        "Code": "08",
        "Name": "PC"
      },
      "SingleInvGrossProfit": -276.8,
      "LatestCost": 276.8,
      "IsPresent": false,
      "UnitExchangeRate": 120,
      "Quantity2": 0.008333,
      "Unit2": {
        "id": "433",
        "Code": "1",
        "Name": "套"
      },
      "LatestPOrigTaxPrice": 1000,
      "LatestSaleOrigTaxPrice": 5,
      "OrigDiscountAmount": 0,
      "CompositionQuantity": "1平米/0.008333套",
      "OrigTaxPrice": 0,
      "OrigDiscountPrice": 0,
      "TaxRate": 0.03,
      "DiscountRate": 1,
      "OrigTaxAmount": 0,
      "TaxPrice": 0,
      "OrigTax": 0,
      "TaxAmount": 0,
      "DiscountPrice": 0,
      "IsClose": false,
      "DiscountAmount": 0,
      "Tax": 0,
      "PriceStrategyTypeName": "",
      "Discount": 0,
      "DeliveryDate": new Date("1900-12-31T16:00:00.000Z"),
      "GrossProfit": -276.8,
      "IsModifiedPrice": false,
      "TaxFlag": false,
      "Code": "0000",
      "PriceStrategySchemeIds": "",
      "PromotionVoucherIds": "",
      "IsMemberIntegral": false,
      "IsPromotionPresent": false,
      "idsaleOrderDTO": 7470,
      "PromotionPresentVoucherCode": "",
      "PromotionSingleVoucherCode": "",
      "HasPRA": false,
      "priuserdefdecm2": 0,
      "PriceStrategySchemeNames": "",
      "PromotionVoucherCodes": "",
      "PromotionPresentBatchInfo": "",
      "PromotionPresentBatchType": "",
      "PromotionPriceBatchInfo": "",
      "PromotionPriceBatchType": "",
      "PromotionBatchMemo": "",
      "priuserdefdecm1": 0,
      "priuserdefdecm3": 0,
      "priuserdefdecm4": 1,
      "pubuserdefnvc3": "1平米/0.008333套",
      "pubuserdefdecm3": 1,
      "Warehouse": {
        "id": 362,
        "Code": "00",
        "Name": "a"
      },
      "Ts": "00000000098e3f45",
      "Status": 0,
      "id": "10664"
    }
  ],
  "status": "invalid",
  "createBy": "user001",
  "createAt": new Date("2019-08-29T09:00:54.040Z"),
  "updateBy": "user001",
  "updateAt": new Date("2019-08-29T09:00:54.040Z"),
  "ts": "1567069254040",
  "id": "1q_ZZolWRB"
}
